name = "beige"
appearance = "light"
description = "beige and charcoal"
override = false

[colors]
bg            = "#d1cdb7"
bg_panel      = "#dad6c1"
bg_card       = "#e2dfcb"
bg_track      = "#c4bfa8"
bg_hover      = "#b8b39b"
fg            = "#454138"
fg_soft       = "#57534a"
fg_dim        = "#6e6a5c"
fg_muted      = "#8a8573"
fg_faint      = "#aaa590"
fg_dark       = "#99947e"
accent        = "#454138"
highlight     = "#a0522d"
border        = "#c2bda6"
border_strong = "#454138"
border_accent = "#aaa58f"
danger        = "#b83a2a"
urgent        = "#d0583f"
ok            = "#5f8048"

cursor       = "#454138"
cursor_text  = "#d1cdb7"
selection_bg = "#454138"
selection_fg = "#dcd8c0"
url          = "#4a6a85"
term0  = "#454138"
term1  = "#a8412f"
term2  = "#5a7a45"
term3  = "#8a7430"
term4  = "#4a6a85"
term5  = "#7a5a80"
term6  = "#4a7a75"
term7  = "#6a6555"
term8  = "#78735f"
term9  = "#c0503a"
term10 = "#6f9455"
term11 = "#a38a3a"
term12 = "#5a80a0"
term13 = "#946a9a"
term14 = "#5a9490"
term15 = "#2e2b25"

wb_panel_bg    = "#c8c3ad"
wb_text        = "#454138"
wb_critical    = "#b83a2a"
wb_ws_idle     = "#8a8573"
wb_ws_active   = "#454138"
wb_ws_urgent   = "#d0583f"

lock_outline  = "#454138"
lock_check    = "#5f8048"
lock_fail     = "#b83a2a"
lock_font     = "#57534a"
lock_date     = "#454138"
lock_media    = "#454138"
lock_password = "#454138"
lock_time     = "#454138"
lock_layout   = "#8a8573"

gtk_bg = "#d1cdb7"
gtk_fg = "#454138"

qs_bg            = "#d1cdb7"
qs_text          = "#454138"
qs_text_dim      = "#6e6a5c"
qs_danger        = "#b83a2a"
qs_accent        = "#454138"
qs_accent2       = "#a0522d"
qs_border        = "#c2bda6"
qs_bg_panel      = "#dad6c1"
qs_bg_card       = "#e2dfcb"
qs_border_accent = "#aaa58f"
qs_text_faint    = "#aaa590"
qs_ok            = "#5f8048"
qs_track_bg      = "#c4bfa8"
