name = "catppuccin-mocha"
appearance = "dark"
description = "Catppuccin Mocha theme"
override = false   # true = wallpaper changes will NOT replace this preset

[colors]
bg            = "#1e1e2e"
bg_panel      = "#181825"
bg_card       = "#313244"
bg_track      = "#45475a"
bg_hover      = "#585b70"
fg            = "#cdd6f4"
fg_soft       = "#bac2de"
fg_dim        = "#a6adc8"
fg_muted      = "#7f849c"
fg_faint     = "#585b70"
fg_dark       = "#45475a"
accent        = "#89b4fa"
highlight     = "#74c7ec"
border        = "#313244"
border_strong = "#89b4fa"
border_accent = "#45475a"
danger        = "#f38ba8"
urgent        = "#eba0ac"
ok            = "#a6e3a1"

cursor       = "#f5e0e6"
cursor_text  = "#1e1e2e"
selection_bg = "#45475a"
selection_fg = "#cdd6f4"
url          = "#89dceb"

term0  = "#45475a"
term1  = "#f38ba8"
term2  = "#a6e3a1"
term3  = "#f9e2af"
term4  = "#89b4fa"
term5  = "#f5c2e7"
term6  = "#94e2d5"
term7  = "#bac2de"
term8  = "#585b70"
term9  = "#f38ba8"
term10 = "#a6e3a1"
term11 = "#f9e2af"
term12 = "#89b4fa"
term13 = "#f5c2e7"
term14 = "#94e2d5"
term15 = "#cdd6f4"

wb_panel_bg    = "#181825"
wb_text        = "#cdd6f4"
wb_critical    = "#f38ba8"
wb_ws_idle     = "#585b70"
wb_ws_active   = "#89b4fa"
wb_ws_urgent   = "#eba0ac"

lock_outline  = "#89b4fa"
lock_check    = "#a6e3a1"
lock_fail     = "#f38ba8"
lock_font     = "#bac2de"
lock_date     = "#74c7ec"
lock_media    = "#cba6f7"
lock_password = "#cdd6f4"
lock_time     = "#89b4fa"
lock_layout   = "#585b70"

gtk_bg = "#1e1e2e"
gtk_fg = "#cdd6f4"

qs_bg            = "#1e1e2e"   # alpha handled separately, see below
qs_text          = "#cdd6f4"
qs_text_dim      = "#bac2de"
qs_danger        = "#f38ba8"
qs_accent        = "#89b4fa"
qs_accent2       = "#cba6f7"
qs_border        = "#313244"
qs_bg_panel      = "#181825"
qs_bg_card       = "#313244"
qs_border_accent = "#45475a"
qs_text_faint    = "#585b70"
qs_ok            = "#a6e3a1"
qs_track_bg      = "#45475a"

