name = "dracula"
appearance = "dark"
description = "Dark Dracula theme"
override = false

[colors]
bg            = "#191a21"
bg_panel      = "#21222c"
bg_card       = "#282a36"
bg_track      = "#343746"
bg_hover      = "#44475a"
fg            = "#f8f8f2"
fg_soft       = "#e6e6e0"
fg_dim        = "#b6b8c8"
fg_muted      = "#8b93bd"
fg_faint      = "#6272a4"
fg_dark       = "#44475a"
accent        = "#bd93f9"
highlight     = "#8be9fd"
border        = "#343746"
border_strong = "#bd93f9"
border_accent = "#44475a"
danger        = "#ff5555"
urgent        = "#ff6e6e"
ok            = "#50fa7b"

cursor       = "#f8f8f2"
cursor_text  = "#282a36"
selection_bg = "#44475a"
selection_fg = "#f8f8f2"
url          = "#8be9fd"

term0  = "#21222c"
term1  = "#ff5555"
term2  = "#50fa7b"
term3  = "#f1fa8c"
term4  = "#bd93f9"
term5  = "#ff79c6"
term6  = "#8be9fd"
term7  = "#f8f8f2"
term8  = "#6272a4"
term9  = "#ff6e6e"
term10 = "#69ff94"
term11 = "#ffffa5"
term12 = "#d6acff"
term13 = "#ff92df"
term14 = "#a4ffff"
term15 = "#ffffff"

lock_outline  = "#bd93f9"
lock_check    = "#50fa7b"
lock_fail     = "#ff5555"
lock_font     = "#e6e6e0"
lock_date     = "#8be9fd"
lock_media    = "#ff79c6"
lock_password = "#f8f8f2"
lock_time     = "#bd93f9"
lock_layout   = "#6272a4"

gtk_bg = "#191a21"
gtk_fg = "#f8f8f2"

qs_bg            = "#191a21"
qs_text          = "#f8f8f2"
qs_text_dim      = "#e6e6e0"
qs_danger        = "#ff5555"
qs_accent        = "#bd93f9"
qs_accent2       = "#ff79c6"
qs_border        = "#343746"
qs_bg_panel      = "#21222c"
qs_bg_card       = "#282a36"
qs_border_accent = "#44475a"
qs_text_faint    = "#6272a4"
qs_ok            = "#50fa7b"
qs_track_bg      = "#343746"
