name = "43pr-gold"
description = "Black and gold"
override = false

[colors]
bg            = "#0a0805"
bg_panel      = "#100d08"
bg_card       = "#18130b"
bg_track      = "#211a10"
bg_hover      = "#2e2415"
fg            = "#f5e9c8"
fg_soft       = "#e3d3a8"
fg_dim        = "#c2b17f"
fg_muted      = "#8f8059"
fg_faint      = "#5a4e33"
fg_dark       = "#766841"
accent        = "#d4af37"
highlight     = "#f0d36b"
border        = "#1c160d"
border_strong = "#d4af37"
border_accent = "#3a2e18"
danger        = "#ff4a3d"
urgent        = "#ff7a5c"
ok            = "#7ed957"

cursor       = "#d4af37"
cursor_text  = "#0a0805"
selection_bg = "#d4af37"
selection_fg = "#0a0805"
url          = "#e8c35a"
term0  = "#0a0805"
term1  = "#c8402f"
term2  = "#7aa83a"
term3  = "#d4af37"
term4  = "#8a8fb8"
term5  = "#b87a6a"
term6  = "#8fb09a"
term7  = "#e3d3a8"
term8  = "#5a4e33"
term9  = "#ff5a48"
term10 = "#98d450"
term11 = "#f0d36b"
term12 = "#a8b0e0"
term13 = "#d89a88"
term14 = "#aed4b8"
term15 = "#f5e9c8"

wb_panel_bg    = "#100d08"
wb_text        = "#f5e9c8"
wb_critical    = "#ff4a3d"
wb_ws_idle     = "#5a4e33"
wb_ws_active   = "#d4af37"
wb_ws_urgent   = "#ff7a5c"

lock_outline  = "#d4af37"
lock_check    = "#7ed957"
lock_fail     = "#ff4a3d"
lock_font     = "#e3d3a8"
lock_date     = "#f0d36b"
lock_media    = "#d4af37"
lock_password = "#f5e9c8"
lock_time     = "#d4af37"
lock_layout   = "#8f8059"

gtk_bg = "#0a0805"
gtk_fg = "#f5e9c8"

qs_bg            = "#0a0805"
qs_text          = "#f5e9c8"
qs_text_dim      = "#c2b17f"
qs_danger        = "#ff4a3d"
qs_accent        = "#d4af37"
qs_accent2       = "#f0d36b"
qs_border        = "#1c160d"
qs_bg_panel      = "#100d08"
qs_bg_card       = "#18130b"
qs_border_accent = "#3a2e18"
qs_text_faint    = "#5a4e33"
qs_ok            = "#7ed957"
qs_track_bg      = "#211a10"
