name = "kanagawa"
description = "Dark Kanagawa theme"
override = false

[colors]
bg            = "#16161d"
bg_panel      = "#1a1a22"
bg_card       = "#1f1f28"
bg_track      = "#2a2a37"
bg_hover      = "#363646"
fg            = "#dcd7ba"
fg_soft       = "#c8c093"
fg_dim        = "#a6a58c"
fg_muted      = "#8a8978"
fg_faint      = "#727169"
fg_dark       = "#54546d"
accent        = "#7e9cd8"
highlight     = "#7fb4ca"
border        = "#2a2a37"
border_strong = "#7e9cd8"
border_accent = "#363646"
danger        = "#e46876"
urgent        = "#ff5d62"
ok            = "#98bb6c"

cursor       = "#c8c093"
cursor_text  = "#1f1f28"
selection_bg = "#2d4f67"
selection_fg = "#c8c093"
url          = "#7fb4ca"

term0  = "#090618"
term1  = "#c34043"
term2  = "#76946a"
term3  = "#c0a36e"
term4  = "#7e9cd8"
term5  = "#957fb8"
term6  = "#6a9589"
term7  = "#c8c093"
term8  = "#727169"
term9  = "#e82424"
term10 = "#98bb6c"
term11 = "#e6c384"
term12 = "#7fb4ca"
term13 = "#938aa9"
term14 = "#7aa89f"
term15 = "#dcd7ba"

wb_panel_bg    = "#1a1a22"
wb_text        = "#dcd7ba"
wb_critical    = "#e46876"
wb_ws_idle     = "#727169"
wb_ws_active   = "#7e9cd8"
wb_ws_urgent   = "#ff5d62"

lock_outline  = "#7e9cd8"
lock_check    = "#98bb6c"
lock_fail     = "#e46876"
lock_font     = "#c8c093"
lock_date     = "#7fb4ca"
lock_media    = "#957fb8"
lock_password = "#dcd7ba"
lock_time     = "#7e9cd8"
lock_layout   = "#727169"

gtk_bg = "#16161d"
gtk_fg = "#dcd7ba"

qs_bg            = "#16161d"
qs_text          = "#dcd7ba"
qs_text_dim      = "#c8c093"
qs_danger        = "#e46876"
qs_accent        = "#7e9cd8"
qs_accent2       = "#957fb8"
qs_border        = "#2a2a37"
qs_bg_panel      = "#1a1a22"
qs_bg_card       = "#1f1f28"
qs_border_accent = "#363646"
qs_text_faint    = "#727169"
qs_ok            = "#98bb6c"
qs_track_bg      = "#2a2a37"
