name = "matrix"
description = "Green phosphor digital rain on black"
override = false

[colors]
bg            = "#000000"
bg_panel      = "#010a02"
bg_card       = "#031205"
bg_track      = "#061c09"
bg_hover      = "#0a2c0f"
fg            = "#00ff41"
fg_soft       = "#00dd38"
fg_dim        = "#00b32d"
fg_muted      = "#008f11"
fg_faint      = "#004d12"
fg_dark       = "#006b14"
accent        = "#00ff41"
highlight     = "#7dffa0"
border        = "#031a06"
border_strong = "#00ff41"
border_accent = "#0b4a16"
danger        = "#ff2e2e"
urgent        = "#ff6a3d"
ok            = "#00ff41"

cursor       = "#00ff41"
cursor_text  = "#000000"
selection_bg = "#00ff41"
selection_fg = "#000000"
url          = "#7dffa0"
term0  = "#000000"
term1  = "#b02a2a"
term2  = "#00b32d"
term3  = "#7fbf20"
term4  = "#0a8f5a"
term5  = "#2a9f7a"
term6  = "#00cc99"
term7  = "#a8e6b4"
term8  = "#004d12"
term9  = "#ff4a4a"
term10 = "#00ff41"
term11 = "#b5ff4a"
term12 = "#2fdf9a"
term13 = "#5fffc0"
term14 = "#7dffe0"
term15 = "#d6ffe0"

wb_panel_bg    = "#010a02"
wb_text        = "#00ff41"
wb_critical    = "#ff2e2e"
wb_ws_idle     = "#004d12"
wb_ws_active   = "#00ff41"
wb_ws_urgent   = "#ff6a3d"

lock_outline  = "#00ff41"
lock_check    = "#00ff41"
lock_fail     = "#ff2e2e"
lock_font     = "#00b32d"
lock_date     = "#7dffa0"
lock_media    = "#00dd38"
lock_password = "#00ff41"
lock_time     = "#00ff41"
lock_layout   = "#008f11"

gtk_bg = "#000000"
gtk_fg = "#00ff41"

qs_bg            = "#000000"
qs_text          = "#00ff41"
qs_text_dim      = "#00b32d"
qs_danger        = "#ff2e2e"
qs_accent        = "#00ff41"
qs_accent2       = "#7dffa0"
qs_border        = "#031a06"
qs_bg_panel      = "#010a02"
qs_bg_card       = "#031205"
qs_border_accent = "#0b4a16"
qs_text_faint    = "#004d12"
qs_ok            = "#00ff41"
qs_track_bg      = "#061c09"
