name = "nord"
appearance = "dark"
description = "Nord theme"
override = false   # true = wallpaper changes will NOT replace this preset

[colors]
bg            = "#2e3440"
bg_panel      = "#292e39"
bg_card       = "#3b4252"
bg_track      = "#434c5e"
bg_hover      = "#4c566a"
fg            = "#eceff4"
fg_soft       = "#e5e9f0"
fg_dim       = "#d8dee9"
fg_muted     = "#aeb9cc"
fg_faint     = "#687386"
fg_dark      = "#616b7c"
accent        = "#88c0d0"
highlight     = "#81a1c1"
border        = "#434c5e"
border_strong = "#88c0d0"
border_accent = "#4c566a"
danger        = "#bf616a"
urgent        = "#d08770"
ok            = "#a3be8c"

cursor       = "#eceff4"
cursor_text  = "#2e3440"
selection_bg = "#4c566a"
selection_fg = "#eceff4"
url          = "#88c0d0"

term0  = "#2e3440"
term1  = "#bf616a"
term2  = "#a3be8c"
term3  = "#ebcb8b"
term4  = "#81a1c1"
term5  = "#b48ead"
term6  = "#88c0d0"
term7  = "#e5e9f0"
term8  = "#4c566a"
term9  = "#bf616a"
term10 = "#a3be8c"
term11 = "#ebcb8b"
term12 = "#81a1c1"
term13 = "#b48ead"
term14 = "#8fbcbb"
term15 = "#eceff4"

lock_outline  = "#88c0d0"
lock_check    = "#a3be8c"
lock_fail     = "#bf616a"
lock_font     = "#d8dee9"
lock_date     = "#81a1c1"
lock_media    = "#b48ead"
lock_password = "#eceff4"
lock_time     = "#88c0d0"
lock_layout   = "#687386"

gtk_bg = "#2e3440"
gtk_fg = "#eceff4"

qs_bg            = "#2e3440"   # alpha handled separately, see below
qs_text          = "#eceff4"
qs_text_dim      = "#d8dee9"
qs_danger        = "#bf616a"
qs_accent        = "#88c0d0"
qs_accent2       = "#81a1c1"
qs_border        = "#434c5e"
qs_bg_panel      = "#292e39"
qs_bg_card       = "#3b4252"
qs_border_accent = "#4c566a"
qs_text_faint    = "#687386"
qs_ok            = "#a3be8c"
qs_track_bg      = "#434c5e"

