name = "one-dark"
appearance = "dark"
description = "Dark One Dark (Atom) theme"
override = false

[colors]
bg            = "#1e2127"
bg_panel      = "#21252b"
bg_card       = "#282c34"
bg_track      = "#2c313c"
bg_hover      = "#3e4451"
fg            = "#abb2bf"
fg_soft       = "#9da5b4"
fg_dim        = "#828997"
fg_muted      = "#6b7385"
fg_faint      = "#5c6370"
fg_dark       = "#4b5263"
accent        = "#61afef"
highlight     = "#56b6c2"
border        = "#2c313c"
border_strong = "#61afef"
border_accent = "#3e4451"
danger        = "#e06c75"
urgent        = "#f0848d"
ok            = "#98c379"

cursor       = "#528bff"
cursor_text  = "#282c34"
selection_bg = "#3e4451"
selection_fg = "#abb2bf"
url          = "#56b6c2"

term0  = "#282c34"
term1  = "#e06c75"
term2  = "#98c379"
term3  = "#e5c07b"
term4  = "#61afef"
term5  = "#c678dd"
term6  = "#56b6c2"
term7  = "#abb2bf"
term8  = "#5c6370"
term9  = "#e06c75"
term10 = "#98c379"
term11 = "#e5c07b"
term12 = "#61afef"
term13 = "#c678dd"
term14 = "#56b6c2"
term15 = "#ffffff"

wb_panel_bg    = "#21252b"
wb_text        = "#abb2bf"
wb_critical    = "#e06c75"
wb_ws_idle     = "#5c6370"
wb_ws_active   = "#61afef"
wb_ws_urgent   = "#f0848d"

lock_outline  = "#61afef"
lock_check    = "#98c379"
lock_fail     = "#e06c75"
lock_font     = "#9da5b4"
lock_date     = "#56b6c2"
lock_media    = "#c678dd"
lock_password = "#abb2bf"
lock_time     = "#61afef"
lock_layout   = "#5c6370"

gtk_bg = "#1e2127"
gtk_fg = "#abb2bf"

qs_bg            = "#1e2127"
qs_text          = "#abb2bf"
qs_text_dim      = "#9da5b4"
qs_danger        = "#e06c75"
qs_accent        = "#61afef"
qs_accent2       = "#c678dd"
qs_border        = "#2c313c"
qs_bg_panel      = "#21252b"
qs_bg_card       = "#282c34"
qs_border_accent = "#3e4451"
qs_text_faint    = "#5c6370"
qs_ok            = "#98c379"
qs_track_bg      = "#2c313c"
