name = "red"
description = "Arasaka-style red on black"
override = false

[colors]
bg            = "#0a0506"
bg_panel      = "#100809"
bg_card       = "#190c0e"
bg_track      = "#231214"
bg_hover      = "#351a1d"
fg            = "#f5e6e6"
fg_soft       = "#e0cccc"
fg_dim        = "#b89c9c"
fg_muted      = "#856a6a"
fg_faint      = "#4f3a3c"
fg_dark       = "#6a5052"
accent        = "#ff003c"
highlight     = "#ff7a5c"
border        = "#1c0d0f"
border_strong = "#ff003c"
border_accent = "#3d1c20"
danger        = "#ff1a1a"
urgent        = "#ff7a5c"
ok            = "#3fd97a"

cursor       = "#ff003c"
cursor_text  = "#0a0506"
selection_bg = "#ff003c"
selection_fg = "#0a0506"
url          = "#ff6a8a"
term0  = "#0a0506"
term1  = "#ff003c"
term2  = "#3fbf6f"
term3  = "#ffb000"
term4  = "#c4344f"
term5  = "#ff2f7a"
term6  = "#ff7a5c"
term7  = "#d8c4c4"
term8  = "#5a3f42"
term9  = "#ff4d6d"
term10 = "#6fff9f"
term11 = "#ffd24d"
term12 = "#e0506a"
term13 = "#ff6ba0"
term14 = "#ffa088"
term15 = "#f5e6e6"

wb_panel_bg    = "#100809"
wb_text        = "#f5e6e6"
wb_critical    = "#ff1a1a"
wb_ws_idle     = "#5a3f42"
wb_ws_active   = "#ff003c"
wb_ws_urgent   = "#ff7a5c"

lock_outline  = "#ff003c"
lock_check    = "#3fd97a"
lock_fail     = "#ff1a1a"
lock_font     = "#e0cccc"
lock_date     = "#ff7a5c"
lock_media    = "#ff2f7a"
lock_password = "#f5e6e6"
lock_time     = "#ff003c"
lock_layout   = "#856a6a"

gtk_bg = "#0a0506"
gtk_fg = "#f5e6e6"

qs_bg            = "#0a0506"
qs_text          = "#f5e6e6"
qs_text_dim      = "#b89c9c"
qs_danger        = "#ff1a1a"
qs_accent        = "#ff003c"
qs_accent2       = "#ff7a5c"
qs_border        = "#1c0d0f"
qs_bg_panel      = "#100809"
qs_bg_card       = "#190c0e"
qs_border_accent = "#3d1c20"
qs_text_faint    = "#4f3a3c"
qs_ok            = "#3fd97a"
qs_track_bg      = "#231214"
