name = "rose-pine"
appearance = "dark"
description = "Dark Rosé Pine theme"
override = false

[colors]
bg            = "#191724"
bg_panel      = "#1f1d2e"
bg_card       = "#26233a"
bg_track      = "#2a2740"
bg_hover      = "#403d52"
fg            = "#e0def4"
fg_soft       = "#c9c6e0"
fg_dim        = "#908caa"
fg_muted      = "#7a7694"
fg_faint      = "#6e6a86"
fg_dark       = "#524f67"
accent        = "#c4a7e7"
highlight     = "#9ccfd8"
border        = "#26233a"
border_strong = "#c4a7e7"
border_accent = "#403d52"
danger        = "#eb6f92"
urgent        = "#f08aa6"
ok            = "#8bd5a8"

cursor       = "#e0def4"
cursor_text  = "#191724"
selection_bg = "#403d52"
selection_fg = "#e0def4"
url          = "#9ccfd8"

term0  = "#26233a"
term1  = "#eb6f92"
term2  = "#31748f"
term3  = "#f6c177"
term4  = "#9ccfd8"
term5  = "#c4a7e7"
term6  = "#ebbcba"
term7  = "#e0def4"
term8  = "#6e6a86"
term9  = "#eb6f92"
term10 = "#31748f"
term11 = "#f6c177"
term12 = "#9ccfd8"
term13 = "#c4a7e7"
term14 = "#ebbcba"
term15 = "#e0def4"

wb_panel_bg    = "#1f1d2e"
wb_text        = "#e0def4"
wb_critical    = "#eb6f92"
wb_ws_idle     = "#6e6a86"
wb_ws_active   = "#c4a7e7"
wb_ws_urgent   = "#f08aa6"

lock_outline  = "#c4a7e7"
lock_check    = "#8bd5a8"
lock_fail     = "#eb6f92"
lock_font     = "#c9c6e0"
lock_date     = "#9ccfd8"
lock_media    = "#ebbcba"
lock_password = "#e0def4"
lock_time     = "#c4a7e7"
lock_layout   = "#6e6a86"

gtk_bg = "#191724"
gtk_fg = "#e0def4"

qs_bg            = "#191724"
qs_text          = "#e0def4"
qs_text_dim      = "#c9c6e0"
qs_danger        = "#eb6f92"
qs_accent        = "#c4a7e7"
qs_accent2       = "#ebbcba"
qs_border        = "#26233a"
qs_bg_panel      = "#1f1d2e"
qs_bg_card       = "#26233a"
qs_border_accent = "#403d52"
qs_text_faint    = "#6e6a86"
qs_ok            = "#8bd5a8"
qs_track_bg      = "#2a2740"
